### ISSUE TITLE
NPM 安装方式使用问题

### ISSUE THREAD

**Issue by liuyami** [gexin1/beautify-qrcode#14]
请多多指教， 是否支持NPM方式安装以及使用方法，安装了“beautify-qrcode” 这个包，但是无法使用

**Comment by gexin1** [comment]
```javascript
npm i beautify-qrcode;    
import {    encodeData,
    renderer25D,
    rendererRect,
    rendererRound,
    rendererRandRound,
    rendererDSJ,
    rendererRandRect,
    rendererImage,
    rendererResImage,} from "beautify-qrcode";
```

**Comment by gexin1** [comment]
这样使用不可以吗

**Comment by liuyami** [comment]
```
import {encodeData, rendererRect} from 'beautify-qrcode';
```

 9: import {encodeData, rendererRect} from 'beautify-qrcode';
            ^
10:
11: export default class Qrcode {
Error: 'encodeData' is not exported by node_modules\beautify-qrcode\dist\beautifyQrcode.js, imported by src\index.js

编译时这样报错

**Comment by gexin1** [comment]
这样看下呢
```javascript
import beautifyQrcode from 'beautify-qrcode';
console.log(beautifyQrcode);
```

**Comment by liuyami** [comment]
> 这样看下呢
> 
> ```js
> import beautifyQrcode from 'beautify-qrcode';
> console.log(beautifyQrcode);
> ```

这样可以的，多谢，另外想了解一下，如何导出jpeg/png 格式的base64，有没有API文档？我看示例网站是可以生成base64的PNG格式图像

**Comment by gexin1** [comment]
使用canvas把svg绘制一下拿到的

**Comment by gexin1** [comment]
我这里边没有添加

**Comment by liuyami** [comment]
> 使用canvas把svg绘制一下拿到的

多谢
