### ISSUE TITLE
请问rendererImage的backgroudImage是什么？

### ISSUE THREAD

**Issue by rulaishenzhang** [gexin1/beautify-qrcode#8]
我在小程序里看到选择了图片之后，是类似这样的：http://tmp/wx1a6eeeab6bce4ce3.o6zAJs4jXxveaXecN 的图片地址。

但是我把这个图片地址放到backgroudImage参数，二维码却没有出现
`
let qrcode = encodeData({
          text: 'https://www.baidu.com',
          correctLevel: 0,
      });
let A1 = rendererImage(qrcode, {
        backgroudImage: res.tempFilePaths[0],
      });
`
res.tempFilePaths[0]是wx.chooseImage选择相册文件后得到的临时图片地址

**Comment by gexin1** [comment]
等我把处理方法验证完了 会写一篇如何在微信小程序处理的例子 
最近有点忙😅

**Comment by rulaishenzhang** [comment]
好的，期待你的文档哦

**Comment by gexin1** [comment]
-   rendererResImage 可能需要使用小程序的canvas做一下适配
-   微信小程序 image 需要转换为 base64 svg 才能正常显示
-   rendererImage backgroudImage 就是 svg image 的 [xlink:href=] 使用小程序临时路径也是可以展示的
-   尝试了下 cax 部分二维码并不能很好展示
- 暂时使用小程序没有找到方法来转换svg 为png、jpg 来保存到用户本地 我使用sharp库在服务端做转换

```html
    <image src="{{qrcode}}" mode="widthFix"></image>
```
```javascript
import { Base64 } from 'js-base64';
const base64Svg = rendererRect(qrcode, options);
const qrcode= `data:image/svg+xml;base64,` + Base64.encode(base64Svg);

```

**Comment by rulaishenzhang** [comment]
好，那我也整服务端吧，多谢了
